FROM nginx:alpine

# Remove default nginx static assets
RUN rm -rf /usr/share/nginx/html/*

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY . /usr/share/nginx/html

# Optimizations could go here (gzip, cache control headers in nginx.conf)
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
