"""initial_ai_os_schema

Revision ID: 558e39301e77
Revises: 
Create Date: 2026-07-23 12:46:20.235746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.database.connection import Base
import app.models.models  # noqa: F401 - register the complete V1 schema


# revision identifiers, used by Alembic.
revision: str = '558e39301e77'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the complete V1 baseline on an empty database.

    This revision replaced an autogeneration performed against a populated
    legacy database.  Alembic, not FastAPI startup, owns schema creation.
    """
    Base.metadata.create_all(bind=op.get_bind())
    return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_outbox',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_outbox_event_type'), 'event_outbox', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_outbox_id'), 'event_outbox', ['id'], unique=False)
    op.create_table('goal_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('structure_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_templates_id'), 'goal_templates', ['id'], unique=False)
    op.create_table('decision_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('input_state_hash', sa.String(), nullable=True),
    sa.Column('decision_json', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_logs_id'), 'decision_logs', ['id'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_id'), 'memories', ['id'], unique=False)
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_data_id'), 'user_data', ['id'], unique=False)
    op.create_index(op.f('ix_user_data_user_id'), 'user_data', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('career_stage', sa.String(), nullable=True),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('background_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('workflow_states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workflow_type', sa.String(), nullable=True),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('context_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_states_id'), 'workflow_states', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_states_workflow_type'), 'workflow_states', ['workflow_type'], unique=False)
    op.create_table('goal_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=True),
    sa.Column('depends_on_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_dependencies_id'), 'goal_dependencies', ['id'], unique=False)
    op.create_table('goal_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('snapshot_json', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_versions_id'), 'goal_versions', ['id'], unique=False)
    op.drop_index(op.f('ix_messages_session_timestamp'), table_name='chat_messages')
    op.add_column('documents', sa.Column('workspace_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'documents', 'workspaces', ['workspace_id'], ['id'])
    op.add_column('goals', sa.Column('parent_id', sa.String(), nullable=True))
    op.add_column('goals', sa.Column('type', sa.String(), nullable=True))
    op.add_column('goals', sa.Column('health_score', sa.Float(), nullable=True))
    op.add_column('goals', sa.Column('is_ai_managed', sa.Boolean(), nullable=True))
    op.add_column('goals', sa.Column('reasoning', sa.Text(), nullable=True))
    op.add_column('goals', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('goals', sa.Column('source', sa.String(), nullable=True))
    op.create_foreign_key(None, 'goals', 'goals', ['parent_id'], ['id'])
    op.add_column('job_applications', sa.Column('workspace_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'job_applications', 'workspaces', ['workspace_id'], ['id'])
    op.add_column('notes', sa.Column('workspace_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'notes', 'workspaces', ['workspace_id'], ['id'])
    op.add_column('resumes', sa.Column('workspace_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'resumes', 'workspaces', ['workspace_id'], ['id'])
    op.add_column('users', sa.Column('persona', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove the disposable V1 baseline schema."""
    Base.metadata.drop_all(bind=op.get_bind())
    return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'persona')
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_column('resumes', 'workspace_id')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'workspace_id')
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    op.drop_column('job_applications', 'workspace_id')
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_column('goals', 'source')
    op.drop_column('goals', 'confidence')
    op.drop_column('goals', 'reasoning')
    op.drop_column('goals', 'is_ai_managed')
    op.drop_column('goals', 'health_score')
    op.drop_column('goals', 'type')
    op.drop_column('goals', 'parent_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'workspace_id')
    op.create_index(op.f('ix_messages_session_timestamp'), 'chat_messages', ['session_id', 'timestamp'], unique=False)
    op.drop_index(op.f('ix_goal_versions_id'), table_name='goal_versions')
    op.drop_table('goal_versions')
    op.drop_index(op.f('ix_goal_dependencies_id'), table_name='goal_dependencies')
    op.drop_table('goal_dependencies')
    op.drop_index(op.f('ix_workflow_states_workflow_type'), table_name='workflow_states')
    op.drop_index(op.f('ix_workflow_states_id'), table_name='workflow_states')
    op.drop_table('workflow_states')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_data_user_id'), table_name='user_data')
    op.drop_index(op.f('ix_user_data_id'), table_name='user_data')
    op.drop_table('user_data')
    op.drop_index(op.f('ix_memories_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_decision_logs_id'), table_name='decision_logs')
    op.drop_table('decision_logs')
    op.drop_index(op.f('ix_goal_templates_id'), table_name='goal_templates')
    op.drop_table('goal_templates')
    op.drop_index(op.f('ix_event_outbox_id'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_event_type'), table_name='event_outbox')
    op.drop_table('event_outbox')
    # ### end Alembic commands ###
