"""Add ondelete CASCADE and RefreshToken

Revision ID: 6297327ece39
Revises: b9f484181401
Create Date: 2026-08-07 15:37:57.572909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6297327ece39'
down_revision: Union[str, Sequence[str], None] = 'b9f484181401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Included in the reconstructed empty-database baseline.
    return
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('certification_planner', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_certification_planner_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_certification_planner_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chat_sessions_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_chat_sessions_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('daily_missions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_daily_missions_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_daily_missions_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('decision_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_decision_logs_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_decision_logs_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('degree_tracker', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_degree_tracker_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_degree_tracker_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_documents_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_documents_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('experiment_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_experiment_logs_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_experiment_logs_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('health_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_ai_managed', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_goals_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_goals_parent_id_goals'), 'goals', ['parent_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_goals_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('higher_education_plans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_higher_education_plans_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_higher_education_plans_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_interview_sessions_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_interview_sessions_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_job_applications_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_job_applications_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('learning_roadmaps', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_learning_roadmaps_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_learning_roadmaps_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('literature_papers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_literature_papers_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_literature_papers_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_memories_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_memories_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notes_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_notes_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notifications_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_notifications_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('placement_tracker', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_placement_tracker_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_placement_tracker_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_projects_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_projects_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('publication_tracker', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_publication_tracker_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_publication_tracker_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_resumes_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_resumes_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('thesis_projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_thesis_projects_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_thesis_projects_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_data_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_data_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('profile_photo_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('degree', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('branch', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('college', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('university', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('graduation_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cgpa', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('preferred_domains_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preferred_industries_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preferred_locations_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('salary_expectations', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('work_authorization', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('work_preferences_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notification_preferences_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('soft_skills_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('languages_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('certifications_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('current_resume_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('resume_version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resume_ats_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resume_last_parsed', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('portfolio_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('leetcode_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('hackerrank_url', sa.String(length=512), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_user_profiles_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_profiles_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_user_profiles_current_resume_id_resumes'), 'resumes', ['current_resume_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('workflow_states', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_workflow_states_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_workflow_states_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_workspaces_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_workspaces_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    return
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_workspaces_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_workspaces_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('workflow_states', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_workflow_states_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_workflow_states_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_profiles_current_resume_id_resumes'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_profiles_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_profiles_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('hackerrank_url')
        batch_op.drop_column('leetcode_url')
        batch_op.drop_column('portfolio_url')
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('github_url')
        batch_op.drop_column('resume_last_parsed')
        batch_op.drop_column('resume_ats_score')
        batch_op.drop_column('resume_version')
        batch_op.drop_column('current_resume_id')
        batch_op.drop_column('certifications_json')
        batch_op.drop_column('languages_json')
        batch_op.drop_column('soft_skills_json')
        batch_op.drop_column('timezone')
        batch_op.drop_column('notification_preferences_json')
        batch_op.drop_column('work_preferences_json')
        batch_op.drop_column('work_authorization')
        batch_op.drop_column('salary_expectations')
        batch_op.drop_column('preferred_locations_json')
        batch_op.drop_column('preferred_industries_json')
        batch_op.drop_column('preferred_domains_json')
        batch_op.drop_column('cgpa')
        batch_op.drop_column('graduation_year')
        batch_op.drop_column('university')
        batch_op.drop_column('college')
        batch_op.drop_column('branch')
        batch_op.drop_column('degree')
        batch_op.drop_column('profile_photo_url')
        batch_op.drop_column('phone')

    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_data_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_data_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('thesis_projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_thesis_projects_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_thesis_projects_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_resumes_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_resumes_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('publication_tracker', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_publication_tracker_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_publication_tracker_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_projects_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_projects_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('placement_tracker', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_placement_tracker_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_placement_tracker_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notifications_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_notifications_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notes_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_notes_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_memories_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_memories_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('literature_papers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_literature_papers_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_literature_papers_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('learning_roadmaps', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_learning_roadmaps_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_learning_roadmaps_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_job_applications_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_job_applications_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_interview_sessions_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_interview_sessions_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('higher_education_plans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_higher_education_plans_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_higher_education_plans_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_goals_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_goals_parent_id_goals'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_goals_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('is_ai_managed')
        batch_op.drop_column('health_score')
        batch_op.drop_column('type')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('experiment_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_experiment_logs_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_experiment_logs_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_documents_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_documents_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('degree_tracker', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_degree_tracker_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_degree_tracker_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('decision_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_decision_logs_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_decision_logs_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('daily_missions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_daily_missions_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_daily_missions_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chat_sessions_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_chat_sessions_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('certification_planner', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_certification_planner_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_certification_planner_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_id'))

    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
