"""Add Resume versioning and status batch

Revision ID: b9f484181401
Revises: 124d080d546c
Create Date: 2026-08-01 12:38:44.941119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f484181401'
down_revision: Union[str, Sequence[str], None] = '124d080d546c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Included in the reconstructed empty-database baseline.
    return
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'workspaces', ['workspace_id'], ['id'])

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('source')
        batch_op.drop_column('is_ai_managed')
        batch_op.drop_column('reasoning')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('confidence')
        batch_op.drop_column('health_score')

    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'workspaces', ['workspace_id'], ['id'])

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'workspaces', ['workspace_id'], ['id'])
        batch_op.drop_column('is_pinned')
        batch_op.drop_column('source_topic')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parsing_status', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'workspaces', ['workspace_id'], ['id'])
        batch_op.drop_column('target_role')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'resumes', ['current_resume_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    return
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('target_role', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parsing_status')
        batch_op.drop_column('version')
        batch_op.drop_column('file_size')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('source_topic', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('is_pinned', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health_score', sa.FLOAT(), server_default=sa.text('(1.0)'), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.FLOAT(), server_default=sa.text('(1.0)'), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('reasoning', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('is_ai_managed', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('source', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), server_default=sa.text("'GOAL'"), nullable=True))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
