"""add_feedback_events_analytics_columns

Revision ID: d065b80bd055
Revises: 1e68704a7138
Create Date: 2026-09-12 12:53:20.540513

"""
from typing import Sequence, Union

from alembic import context, op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd065b80bd055'
down_revision: Union[str, Sequence[str], None] = '1e68704a7138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The reconstructed initial revision (558e39301e77) calls Base.metadata.create_all()
    # which builds the FINAL target schema for a fresh database — including every
    # column, index, and FK that this migration would otherwise add/drop/rename.
    # On a fresh install, therefore, this migration's batch operations must be
    # skipped entirely (they'd raise DuplicateColumn / CannotDropObject errors).
    # On a legacy database whose schema predates the reconstruction, the legacy
    # columns (profile_id, website, contact_role, biggest_hiring_challenge, etc.)
    # are still present and the new columns (session_id, consent_id, ai_insight,
    # dedup_hash, etc.) are still absent, so we run the full migration body.
    if context.is_offline_mode():
        return

    inspector = sa.inspect(op.get_bind())
    company_columns = {column["name"] for column in inspector.get_columns("company_profiles")}
    fresh_schema_signals = ["session_id", "consent_id", "company_type"]
    if all(c in company_columns for c in fresh_schema_signals):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('consent_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('company_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hiring_locations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('roles_hired', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('experience_levels', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skills_commonly_required', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contact_linkedin', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_company_profiles_profile_id'))
        batch_op.create_index(batch_op.f('ix_company_profiles_session_id'), ['session_id'], unique=True)
        batch_op.drop_constraint(batch_op.f('fk_company_profiles_profile_id_user_discovery_profiles'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_company_profiles_consent_id_consent_records'), 'consent_records', ['consent_id'], ['id'])
        batch_op.drop_column('contact_role')
        batch_op.drop_column('hiring_plans')
        batch_op.drop_column('profile_id')
        batch_op.drop_column('website')

    with op.batch_alter_table('contact_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consent_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contact_permission', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('admin_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))
        batch_op.alter_column('role_type',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_contact_requests_email'))
        batch_op.create_index('ix_contact_requests_category', ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_requests_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_contact_requests_status', ['status'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_contact_requests_consent_id_consent_records'), 'consent_records', ['consent_id'], ['id'])

    with op.batch_alter_table('feedback_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_type', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('score_sum', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_avg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ai_insight', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_insight_generated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('period', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('period_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('period_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('event_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_feedback_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_feedback_events_type_entity', ['event_type', 'entity_id'], unique=False)

    with op.batch_alter_table('hiring_signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finding_qualified_candidates', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('too_many_irrelevant_applications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('skill_mismatch', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('resume_quality', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('candidate_screening', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('interview_readiness', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('candidate_availability', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('discovering_talent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hiring_speed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hiring_challenge_other', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('wants_candidate_discovery', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wants_skill_matching', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wants_resume_intelligence', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wants_skill_gap_insights', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wants_opportunity_distribution', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wants_hiring_analytics', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wants_candidate_recommendations', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wants_hiring_intelligence', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('what_platforms_miss', sa.Text(), nullable=True))
        batch_op.drop_column('interested_in_saarthi_hire')
        batch_op.drop_column('biggest_hiring_challenge')
        batch_op.drop_column('skills_needed')
        batch_op.drop_column('roles_hiring_for')
        batch_op.drop_column('experience_levels')

    with op.batch_alter_table('job_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('experience_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('experience_max', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('public_job_url', sa.String(length=2048), nullable=False))
        batch_op.add_column(sa.Column('source_url', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('optional_hiring_contact', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('additional_information', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dedup_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('sync_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('validation_errors', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dedup_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('synced_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_job_submissions_dedup_hash'), ['dedup_hash'], unique=False)
        batch_op.drop_column('salary_range')
        batch_op.drop_column('jd_text')
        batch_op.drop_column('title')
        batch_op.drop_column('apply_link')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apply_link', sa.VARCHAR(length=2048), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('jd_text', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('salary_range', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('ix_job_submissions_dedup_hash'))
        batch_op.drop_column('synced_at')
        batch_op.drop_column('dedup_hash')
        batch_op.drop_column('validation_errors')
        batch_op.drop_column('sync_status')
        batch_op.drop_column('dedup_status')
        batch_op.drop_column('additional_information')
        batch_op.drop_column('optional_hiring_contact')
        batch_op.drop_column('source_url')
        batch_op.drop_column('public_job_url')
        batch_op.drop_column('skills')
        batch_op.drop_column('experience_max')
        batch_op.drop_column('experience_min')
        batch_op.drop_column('role')
        batch_op.drop_column('company')

    with op.batch_alter_table('hiring_signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_levels', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('roles_hiring_for', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('skills_needed', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('biggest_hiring_challenge', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('interested_in_saarthi_hire', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('what_platforms_miss')
        batch_op.drop_column('wants_hiring_intelligence')
        batch_op.drop_column('wants_candidate_recommendations')
        batch_op.drop_column('wants_hiring_analytics')
        batch_op.drop_column('wants_opportunity_distribution')
        batch_op.drop_column('wants_skill_gap_insights')
        batch_op.drop_column('wants_resume_intelligence')
        batch_op.drop_column('wants_skill_matching')
        batch_op.drop_column('wants_candidate_discovery')
        batch_op.drop_column('hiring_challenge_other')
        batch_op.drop_column('hiring_speed')
        batch_op.drop_column('discovering_talent')
        batch_op.drop_column('candidate_availability')
        batch_op.drop_column('interview_readiness')
        batch_op.drop_column('candidate_screening')
        batch_op.drop_column('resume_quality')
        batch_op.drop_column('skill_mismatch')
        batch_op.drop_column('too_many_irrelevant_applications')
        batch_op.drop_column('finding_qualified_candidates')

    with op.batch_alter_table('feedback_events', schema=None) as batch_op:
        batch_op.drop_index('ix_feedback_events_type_entity')
        batch_op.drop_index(batch_op.f('ix_feedback_events_session_id'))
        batch_op.alter_column('event_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('status')
        batch_op.drop_column('period_end')
        batch_op.drop_column('period_start')
        batch_op.drop_column('period')
        batch_op.drop_column('ai_insight_generated_at')
        batch_op.drop_column('ai_insight')
        batch_op.drop_column('score_count')
        batch_op.drop_column('score_avg')
        batch_op.drop_column('score_sum')
        batch_op.drop_column('count')
        batch_op.drop_column('entity_type')

    with op.batch_alter_table('contact_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_contact_requests_consent_id_consent_records'), type_='foreignkey')
        batch_op.drop_index('ix_contact_requests_status')
        batch_op.drop_index(batch_op.f('ix_contact_requests_session_id'))
        batch_op.drop_index('ix_contact_requests_category')
        batch_op.create_index(batch_op.f('ix_contact_requests_email'), ['email'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('role_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
        batch_op.drop_column('source')
        batch_op.drop_column('admin_notes')
        batch_op.drop_column('contact_permission')
        batch_op.drop_column('category')
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('consent_id')

    with op.batch_alter_table('company_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.VARCHAR(length=512), nullable=True))
        batch_op.add_column(sa.Column('profile_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('hiring_plans', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('contact_role', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_company_profiles_consent_id_consent_records'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_company_profiles_profile_id_user_discovery_profiles'), 'user_discovery_profiles', ['profile_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_company_profiles_session_id'))
        batch_op.create_index(batch_op.f('ix_company_profiles_profile_id'), ['profile_id'], unique=False)
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('source')
        batch_op.drop_column('contact_linkedin')
        batch_op.drop_column('skills_commonly_required')
        batch_op.drop_column('experience_levels')
        batch_op.drop_column('roles_hired')
        batch_op.drop_column('hiring_locations')
        batch_op.drop_column('company_type')
        batch_op.drop_column('consent_id')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
