import { FileText, ShieldAlert, CheckCircle2, Bot } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="flex-1 overflow-y-auto bg-background p-6 md:p-10 space-y-8 text-foreground custom-scrollbar">
      <div className="max-w-4xl mx-auto space-y-4">
        <div className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-4 py-1 text-xs font-semibold text-primary">
          <FileText className="h-3.5 w-3.5" />
          <span>Saarthi AI Terms of Service</span>
        </div>
        <h1 className="text-3xl md:text-5xl font-extrabold tracking-tight font-display">
          Terms of Service & Usage Agreement
        </h1>
        <p className="text-sm text-muted-foreground">
          Last updated: September 14, 2026. Please read these terms before using the Saarthi AI platform.
        </p>
      </div>

      <div className="max-w-4xl mx-auto space-y-6">
        <section className="rounded-2xl border border-border/70 bg-card p-6 md:p-8 space-y-4">
          <h2 className="text-xl font-bold font-display flex items-center gap-2">
            <CheckCircle2 className="h-5 w-5 text-primary" />
            1. Scope of Platform Services
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Saarthi AI provides AI-assisted career planning, resume evaluation, mock interview practice, and opportunity discovery.
            All job listings are aggregated from public sources and recruiter submissions.
          </p>
        </section>

        <section className="rounded-2xl border border-border/70 bg-card p-6 md:p-8 space-y-4">
          <h2 className="text-xl font-bold font-display flex items-center gap-2">
            <Bot className="h-5 w-5 text-primary" />
            2. AI Guidance & Disclaimer
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Recommendations generated by Saarthi AI are classified into <strong>FACT</strong> (direct matching metadata), 
            <strong>INFERENCE</strong> (calculated metrics), and <strong>AI_SUGGESTION</strong> (generative recommendations).
            AI recommendations do not guarantee interview calls, job offers, or admission success.
          </p>
        </section>

        <section className="rounded-2xl border border-border/70 bg-card p-6 md:p-8 space-y-4">
          <h2 className="text-xl font-bold font-display flex items-center gap-2">
            <ShieldAlert className="h-5 w-5 text-primary" />
            3. Opportunity & Signal Submissions
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Recruiters, hiring teams, and community members submitting hiring signals agree to provide authentic job titles, 
            verified apply URLs, and accurate skill requirements. Misleading or spam submissions will be blocked.
          </p>
        </section>
      </div>
    </div>
  );
}
