"""Canonical public feature registry used by Discovery feedback."""

PUBLIC_FEATURES = [
    {
        "id": 1,
        "key": "job_discovery",
        "label": "Smart Job Discovery Engine",
        "group": "Job Matching",
    },
    {
        "id": 2,
        "key": "ats_resume_matching",
        "label": "ATS Resume Match & Score",
        "group": "Job Matching",
    },
    {
        "id": 3,
        "key": "skill_gap_analysis",
        "label": "Role Skill Gap Breakdown",
        "group": "Job Matching",
    },
    {
        "id": 4,
        "key": "company_intelligence",
        "label": "Company Profile & Hiring Signals",
        "group": "Job Matching",
    },
    {
        "id": 5,
        "key": "personalized_job_feed",
        "label": "Personalized Opportunity Feed",
        "group": "Job Matching",
    },
    {
        "id": 6,
        "key": "resume_parser",
        "label": "PDF / DOCX Multi-Resume Parsing",
        "group": "Resume & Profile",
    },
    {
        "id": 7,
        "key": "ats_optimization",
        "label": "ATS Keyword Optimization Suggestions",
        "group": "Resume & Profile",
    },
    {
        "id": 8,
        "key": "portfolio_integrations",
        "label": "GitHub / LinkedIn / Portfolio Sync",
        "group": "Resume & Profile",
    },
    {
        "id": 9,
        "key": "resume_versioning",
        "label": "Resume Versioning & History",
        "group": "Resume & Profile",
    },
    {
        "id": 10,
        "key": "profile_export",
        "label": "Structured Profile Export",
        "group": "Resume & Profile",
    },
    {
        "id": 11,
        "key": "career_copilot_chat",
        "label": "AI Career Copilot Chat Assistant",
        "group": "Career Copilot",
    },
    {
        "id": 12,
        "key": "huggingface_brain",
        "label": "Saarthi AI Brain Model Integration",
        "group": "Career Copilot",
    },
    {
        "id": 13,
        "key": "learning_roadmaps",
        "label": "Personalized Learning Roadmaps",
        "group": "Career Copilot",
    },
    {
        "id": 14,
        "key": "goal_decomposition",
        "label": "AI Goal Decomposition & Milestones",
        "group": "Career Copilot",
    },
    {
        "id": 15,
        "key": "interview_preparation",
        "label": "Mock Interview & Technical Q&A Coach",
        "group": "Career Copilot",
    },
    {
        "id": 16,
        "key": "voice_interviews",
        "label": "Speech-to-Text Interview Practice",
        "group": "Career Copilot",
    },
    {"id": 17, "key": "saved_jobs", "label": "Saved Jobs & Bookmarks", "group": "Applications"},
    {
        "id": 18,
        "key": "application_pipeline",
        "label": "Application Status Pipeline",
        "group": "Applications",
    },
    {
        "id": 19,
        "key": "application_notes",
        "label": "Job Notes & Research Workspace",
        "group": "Applications",
    },
    {
        "id": 20,
        "key": "custom_deadlines",
        "label": "Application Deadline Reminders",
        "group": "Applications",
    },
    {
        "id": 21,
        "key": "salary_insights",
        "label": "Salary Range & Market Benchmarks",
        "group": "Applications",
    },
    {
        "id": 22,
        "key": "graduate_hub",
        "label": "Graduate Hub & Higher Education Tools",
        "group": "Graduate & Higher Ed",
    },
    {
        "id": 23,
        "key": "sop_essay_feedback",
        "label": "SOP & Essay AI Reviewer",
        "group": "Graduate & Higher Ed",
    },
    {
        "id": 24,
        "key": "document_workspaces",
        "label": "Document & Research Workspaces",
        "group": "Workspaces",
    },
    {
        "id": 25,
        "key": "rag_document_search",
        "label": "RAG Multi-Document AI Search",
        "group": "Workspaces",
    },
    {
        "id": 26,
        "key": "project_showcase",
        "label": "Project Showcase Builder",
        "group": "Workspaces",
    },
    {
        "id": 27,
        "key": "career_toolkit",
        "label": "Career Utilities & Calculators",
        "group": "Career Toolkit",
    },
    {
        "id": 28,
        "key": "opportunity_submission",
        "label": "Public Opportunity Signal Submissions",
        "group": "Ecosystem",
    },
    {
        "id": 29,
        "key": "company_hiring_portal",
        "label": "Company Hiring Signal Portal",
        "group": "Ecosystem",
    },
    {
        "id": 30,
        "key": "daily_missions",
        "label": "Daily Career Missions",
        "group": "Career Progress",
    },
    {
        "id": 31,
        "key": "career_health",
        "label": "Career Health & Profile Readiness",
        "group": "Career Progress",
    },
]
